name: Release Native Package

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (patch, minor, major, or specific version)"
        required: true
        default: "patch"

jobs:
  build-native:
    name: Build native binaries (${{ matrix.settings.target }})
    runs-on: ${{ matrix.settings.os }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}

      - name: Setup cross-compilation for macOS
        if: matrix.settings.target == 'aarch64-apple-darwin'
        run: |
          sudo softwareupdate --install-rosetta --agree-to-license

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: cd native && pnpm install

      - name: Build native binary
        run: cd native && pnpm run build --target ${{ matrix.settings.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.settings.target }}
          path: native/*.node

  publish-native:
    needs: build-native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move binaries to native directory
        run: |
          mkdir -p native
          find artifacts -name "*.node" -exec cp {} native/ \;

      - name: Update version
        run: |
          cd native
          VERSION=${{ github.event.inputs.version }}
          if [ "$VERSION" = "patch" ] || [ "$VERSION" = "minor" ] || [ "$VERSION" = "major" ]; then
            npm version $VERSION --no-git-tag-version
          else
            npm version $VERSION --no-git-tag-version
          fi

      - name: Publish to npm
        run: cd native && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
